# automatically generated by the FlatBuffers compiler, do not modify

# namespace: server

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class ProceduralModelListEntry(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProceduralModelListEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProceduralModelListEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # ProceduralModelListEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProceduralModelListEntry
    def ModelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProceduralModelListEntry
    def ContentHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProceduralModelListEntry
    def ModifiedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ProceduralModelListEntry
    def SizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0


def ProceduralModelListEntryStart(builder):
    builder.StartObject(4)


def Start(builder):
    ProceduralModelListEntryStart(builder)


def ProceduralModelListEntryAddModelId(builder, modelId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)


def AddModelId(builder, modelId):
    ProceduralModelListEntryAddModelId(builder, modelId)


def ProceduralModelListEntryAddContentHash(builder, contentHash):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contentHash), 0)


def AddContentHash(builder, contentHash):
    ProceduralModelListEntryAddContentHash(builder, contentHash)


def ProceduralModelListEntryAddModifiedAt(builder, modifiedAt):
    builder.PrependInt64Slot(2, modifiedAt, 0)


def AddModifiedAt(builder, modifiedAt):
    ProceduralModelListEntryAddModifiedAt(builder, modifiedAt)


def ProceduralModelListEntryAddSizeBytes(builder, sizeBytes):
    builder.PrependInt64Slot(3, sizeBytes, 0)


def AddSizeBytes(builder, sizeBytes):
    ProceduralModelListEntryAddSizeBytes(builder, sizeBytes)


def ProceduralModelListEntryEnd(builder):
    return builder.EndObject()


def End(builder):
    return ProceduralModelListEntryEnd(builder)
