# automatically generated by the FlatBuffers compiler, do not modify

# namespace: server

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class ProceduralModelListReply(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProceduralModelListReply()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProceduralModelListReply(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # ProceduralModelListReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProceduralModelListReply
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from ada.comms.fb.server.ProceduralModelListEntry import (
                ProceduralModelListEntry,
            )

            obj = ProceduralModelListEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ProceduralModelListReply
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProceduralModelListReply
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def ProceduralModelListReplyStart(builder):
    builder.StartObject(1)


def Start(builder):
    ProceduralModelListReplyStart(builder)


def ProceduralModelListReplyAddEntries(builder, entries):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)


def AddEntries(builder, entries):
    ProceduralModelListReplyAddEntries(builder, entries)


def ProceduralModelListReplyStartEntriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartEntriesVector(builder, numElems):
    return ProceduralModelListReplyStartEntriesVector(builder, numElems)


def ProceduralModelListReplyEnd(builder):
    return builder.EndObject()


def End(builder):
    return ProceduralModelListReplyEnd(builder)
