# automatically generated by the FlatBuffers compiler, do not modify

# namespace: server

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class ProceduralModelLoad(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProceduralModelLoad()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProceduralModelLoad(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # ProceduralModelLoad
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProceduralModelLoad
    def ModelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def ProceduralModelLoadStart(builder):
    builder.StartObject(1)


def Start(builder):
    ProceduralModelLoadStart(builder)


def ProceduralModelLoadAddModelId(builder, modelId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)


def AddModelId(builder, modelId):
    ProceduralModelLoadAddModelId(builder, modelId)


def ProceduralModelLoadEnd(builder):
    return builder.EndObject()


def End(builder):
    return ProceduralModelLoadEnd(builder)
