# automatically generated by the FlatBuffers compiler, do not modify

# namespace: server

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class ProceduralModelSaveReply(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProceduralModelSaveReply()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProceduralModelSaveReply(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # ProceduralModelSaveReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProceduralModelSaveReply
    def ModelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProceduralModelSaveReply
    def ContentHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def ProceduralModelSaveReplyStart(builder):
    builder.StartObject(2)


def Start(builder):
    ProceduralModelSaveReplyStart(builder)


def ProceduralModelSaveReplyAddModelId(builder, modelId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)


def AddModelId(builder, modelId):
    ProceduralModelSaveReplyAddModelId(builder, modelId)


def ProceduralModelSaveReplyAddContentHash(builder, contentHash):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contentHash), 0)


def AddContentHash(builder, contentHash):
    ProceduralModelSaveReplyAddContentHash(builder, contentHash)


def ProceduralModelSaveReplyEnd(builder):
    return builder.EndObject()


def End(builder):
    return ProceduralModelSaveReplyEnd(builder)
