# automatically generated by the FlatBuffers compiler, do not modify

# namespace: server

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class ServerProcessInfo(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ServerProcessInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsServerProcessInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # ServerProcessInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ServerProcessInfo
    def Pid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ServerProcessInfo
    def ThreadId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ServerProcessInfo
    def LogFilePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def ServerProcessInfoStart(builder):
    builder.StartObject(3)


def Start(builder):
    ServerProcessInfoStart(builder)


def ServerProcessInfoAddPid(builder, pid):
    builder.PrependInt32Slot(0, pid, 0)


def AddPid(builder, pid):
    ServerProcessInfoAddPid(builder, pid)


def ServerProcessInfoAddThreadId(builder, threadId):
    builder.PrependInt32Slot(1, threadId, 0)


def AddThreadId(builder, threadId):
    ServerProcessInfoAddThreadId(builder, threadId)


def ServerProcessInfoAddLogFilePath(builder, logFilePath):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(logFilePath), 0)


def AddLogFilePath(builder, logFilePath):
    ServerProcessInfoAddLogFilePath(builder, logFilePath)


def ServerProcessInfoEnd(builder):
    return builder.EndObject()


def End(builder):
    return ServerProcessInfoEnd(builder)
