// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum CommandType {
  PING = 0,
  PONG = 1,
  UPDATE_SCENE = 2,
  UPDATE_SERVER = 3,
  MESH_INFO_CALLBACK = 4,
  LIST_WEB_CLIENTS = 5
}
