// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CommandType } from './command-type';
import { Error, ErrorT } from '../wsock/error.js';
import { FileObject, FileObjectT } from '../wsock/file-object.js';


export class ServerReply implements flatbuffers.IUnpackableObject<ServerReplyT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ServerReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsServerReply(bb:flatbuffers.ByteBuffer, obj?:ServerReply):ServerReply {
  return (obj || new ServerReply()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsServerReply(bb:flatbuffers.ByteBuffer, obj?:ServerReply):ServerReply {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ServerReply()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fileObject(obj?:FileObject):FileObject|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new FileObject()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

replyTo():CommandType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : CommandType.PING;
}

error(obj?:Error):Error|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Error()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startServerReply(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messageOffset, 0);
}

static addFileObject(builder:flatbuffers.Builder, fileObjectOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, fileObjectOffset, 0);
}

static addReplyTo(builder:flatbuffers.Builder, replyTo:CommandType) {
  builder.addFieldInt8(2, replyTo, CommandType.PING);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, errorOffset, 0);
}

static endServerReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): ServerReplyT {
  return new ServerReplyT(
    this.message(),
    (this.fileObject() !== null ? this.fileObject()!.unpack() : null),
    this.replyTo(),
    (this.error() !== null ? this.error()!.unpack() : null)
  );
}


unpackTo(_o: ServerReplyT): void {
  _o.message = this.message();
  _o.fileObject = (this.fileObject() !== null ? this.fileObject()!.unpack() : null);
  _o.replyTo = this.replyTo();
  _o.error = (this.error() !== null ? this.error()!.unpack() : null);
}
}

export class ServerReplyT implements flatbuffers.IGeneratedObject {
constructor(
  public message: string|Uint8Array|null = null,
  public fileObject: FileObjectT|null = null,
  public replyTo: CommandType = CommandType.PING,
  public error: ErrorT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const message = (this.message !== null ? builder.createString(this.message!) : 0);
  const fileObject = (this.fileObject !== null ? this.fileObject!.pack(builder) : 0);
  const error = (this.error !== null ? this.error!.pack(builder) : 0);

  ServerReply.startServerReply(builder);
  ServerReply.addMessage(builder, message);
  ServerReply.addFileObject(builder, fileObject);
  ServerReply.addReplyTo(builder, this.replyTo);
  ServerReply.addError(builder, error);

  return ServerReply.endServerReply(builder);
}
}
