{{- if and (eq .Values.storage.kind "s3") (not .Values.storage.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-s3" (include "adapy-viewer.fullname" .) }}
  labels: {{- include "adapy-viewer.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.storage.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.s3.secretAccessKey | quote }}
{{- end }}
