name: ada-dev
channels:
  - https://repo.prefix.dev/code-aster
  - conda-forge
dependencies:
  - ada-py
#  - ada-cpp
  - paradoc
  - code-aster
  - occt=*=*novtk*
  - trimesh >=4.1.0
  - python-dotenv
  - pytest