/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * GLTF extension for design and analysis objects
 */
export interface ADADesignAndAnalysisExtension {
  /**
   * Array containing Simulation Data objects
   */
  simulation_objects?: SimulationDataExtensionMetadata[];
  /**
   * Array containing Design Data objects
   */
  design_objects?: DesignDataExtension[];
  /**
   * Version of the ADA GLTF extension schema
   */
  version?: string;
}
export interface SimulationDataExtensionMetadata {
  /**
   * Name of the simulation.
   */
  name: string;
  /**
   * Date and time of the simulation.
   */
  date: string;
  /**
   * Name of the FEA software used.
   */
  fea_software: string;
  /**
   * Version of the FEA software.
   */
  fea_software_version: string;
  /**
   * List of analysis steps.
   */
  steps: StepObject[];
  node_references?: SimNodeReference;
  /**
   * Named groups and their member objects
   */
  groups?: SimGroup[];
  [k: string]: unknown;
}
export interface StepObject {
  /**
   * Type of analysis for this step.
   */
  analysis_type: "eigenvalue" | "implicit static" | "implicit dynamic" | "explicit";
  /**
   * List of field data objects for this step.
   */
  fields: FieldObject[];
  [k: string]: unknown;
}
export interface FieldObject {
  /**
   * Name of the result field, e.g., displacement, stress.
   */
  name: string;
  /**
   * Type of the field data, e.g., 'vector', 'scalar'.
   */
  type: string;
  data: DataReference;
  [k: string]: unknown;
}
export interface DataReference {
  /**
   * Index of the glTF bufferView containing the binary data.
   */
  bufferView: number;
  /**
   * Offset into the bufferView in bytes.
   */
  byteOffset?: number;
  [k: string]: unknown;
}
/**
 * References to GLTF node names
 */
export interface SimNodeReference {
  /**
   * node reference of Point mesh
   */
  points?: string;
  /**
   * node reference of Edges mesh
   */
  edges?: string;
  /**
   * node reference of Faces mesh
   */
  faces?: string;
  /**
   * node reference of Solid Beams mesh
   */
  solid_beams?: string;
  [k: string]: unknown;
}
export interface SimGroup {
  /**
   * Name of group
   */
  name?: string;
  /**
   * Name of group objects
   */
  members?: string[];
  /**
   * Description of Group
   */
  description?: string;
  /**
   * Name of the parent simulation object
   */
  parent_name?: string;
  [k: string]: unknown;
}
/**
 * GLTF extension for design object metadata and grouping
 */
export interface DesignDataExtension {
  /**
   * Name of the design object
   */
  name: string;
  /**
   * Optional description of the design object
   */
  description?: string;
  /**
   * Named groups and their member objects
   */
  groups?: Group[];
  node_references?: DesignNodeReference;
  [k: string]: unknown;
}
export interface Group {
  /**
   * Name of group
   */
  name?: string;
  /**
   * Name of group objects
   */
  members?: string[];
  /**
   * Description of Group
   */
  description?: string;
  /**
   * Name of the parent design object
   */
  parent_name?: string;
  [k: string]: unknown;
}
/**
 * References to GLTF node names
 */
export interface DesignNodeReference {
  /**
   * node reference of Faces mesh
   */
  faces?: string[];
  [k: string]: unknown;
}
