/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * GLTF extension for design and analysis objects
 */
export interface ADADesignAndAnalysisExtension {
  /**
   * Array containing Simulation Data objects
   */
  simulation_objects?: SimulationDataExtensionMetadata[];
  /**
   * Array containing Design Data objects
   */
  design_objects?: DesignDataExtension[];
  /**
   * Version of the ADA GLTF extension schema
   */
  version?: string;
  /**
   * Stable lineage anchor: the source Assembly's guid. CAD and FEA exports derived from the same Assembly share this value so a viewer can match them without name lookups.
   */
  assembly_guid?: string;
}
export interface SimulationDataExtensionMetadata {
  /**
   * Name of the simulation.
   */
  name: string;
  /**
   * Date and time of the simulation.
   */
  date: string;
  /**
   * Name of the FEA software used.
   */
  fea_software: string;
  /**
   * Version of the FEA software.
   */
  fea_software_version: string;
  /**
   * List of analysis steps.
   */
  steps: StepObject[];
  node_references?: SimNodeReference;
  /**
   * Named groups and their member objects
   */
  groups?: SimGroup[];
  stats?: SimStats;
  [k: string]: unknown;
}
export interface StepObject {
  /**
   * Type of analysis for this step.
   */
  analysis_type: "eigenvalue" | "implicit static" | "implicit dynamic" | "explicit";
  /**
   * List of field data objects for this step.
   */
  fields: FieldObject[];
  [k: string]: unknown;
}
export interface FieldObject {
  /**
   * Name of the result field, e.g., displacement, stress.
   */
  name: string;
  /**
   * Type of the field data, e.g., 'vector', 'scalar'.
   */
  type: string;
  data: DataReference;
  [k: string]: unknown;
}
export interface DataReference {
  /**
   * Index of the glTF bufferView containing the binary data.
   */
  bufferView: number;
  /**
   * Offset into the bufferView in bytes.
   */
  byteOffset?: number;
  [k: string]: unknown;
}
/**
 * References to GLTF node names
 */
export interface SimNodeReference {
  /**
   * node reference of Point mesh
   */
  points?: string;
  /**
   * node reference of Edges mesh
   */
  edges?: string;
  /**
   * node reference of Faces mesh
   */
  faces?: string;
  /**
   * node reference of Solid Beams mesh
   */
  solid_beams?: string;
  [k: string]: unknown;
}
export interface SimGroup {
  /**
   * Name of group
   */
  name?: string;
  /**
   * Inline list of element/node names. Used for small groups (default threshold <256); large groups switch to members_buffer_view to keep the JSON chunk size bounded.
   */
  members?: string[];
  /**
   * Index of a glTF bufferView holding the packed uint32 member IDs. Mutually exclusive with `members`. Used for large element groups so the JSON chunk doesn't balloon. The IDs are reconstructed into names by prepending `members_prefix`.
   */
  members_buffer_view?: number;
  /**
   * String prepended to each uint32 ID in members_buffer_view to reconstruct the element/node name (e.g. "EL", "Li", "P"). Required when members_buffer_view is set.
   */
  members_prefix?: string;
  /**
   * Description of Group
   */
  description?: string;
  /**
   * Name of the parent simulation object
   */
  parent_name?: string;
  /**
   * adapy guid of the CAD-side Beam/Plate this SimGroup was meshed from. Lets the viewer link FEA elements back to their CAD parent without name matching. Populated from FemSection.refs[0].guid.
   */
  parent_object_guid?: string;
  /**
   * Type of finite element model objects in this group (nodes or elements)
   */
  fe_object_type?: "node" | "element";
  [k: string]: unknown;
}
/**
 * Aggregate metrics for this simulation model (centre of gravity, element counts). Computed at bake time so the viewer can show per-model info without reloading source.
 */
export interface SimStats {
  cog?: COG;
  /**
   * Number of finite elements per category.
   */
  element_counts?: {
    /**
     * Line / beam elements.
     */
    beam?: number;
    /**
     * Shell elements.
     */
    shell?: number;
    /**
     * Solid elements.
     */
    solid?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Mass-weighted centre of gravity. total_mass and total_volume are zero when elements have no material assigned.
 */
export interface COG {
  x: number;
  y: number;
  z: number;
  /**
   * Sum of contributing masses.
   */
  total_mass?: number;
  /**
   * Sum of contributing volumes.
   */
  total_volume?: number;
  [k: string]: unknown;
}
/**
 * GLTF extension for design object metadata and grouping
 */
export interface DesignDataExtension {
  /**
   * Name of the design object
   */
  name: string;
  /**
   * Optional description of the design object
   */
  description?: string;
  /**
   * Named groups and their member objects
   */
  groups?: Group[];
  node_references?: DesignNodeReference;
  /**
   * Map of physical object name (Beam/Plate/etc.) to its adapy guid. Used by the viewer to resolve a clicked CAD object to its stable lineage id, so a derived FEA model can be matched without name lookups.
   */
  object_guids?: {
    [k: string]: string;
  };
  /**
   * Optional per-object structured metadata (type, section, material, thickness) keyed by object name. When present, the viewer reads it directly from the GLB and skips the server round-trip back to the source IFC for the Properties panel.
   */
  object_metadata?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  stats?: DesignStats;
  /**
   * Per-Connection metadata (one entry per ada.Connection Part in this design model). Lets the inspector show a 'Connections (N)' rollup when a beam/plate is selected — each entry carries spec lineage + the member/weld names that belong to it, so the panel can group otherwise-flat weld lists by their parent Connection without walking the THREE scene graph.
   */
  connections?: ConnectionInfo[];
  [k: string]: unknown;
}
export interface Group {
  /**
   * Name of group
   */
  name?: string;
  /**
   * Name of group objects
   */
  members?: string[];
  /**
   * Description of Group
   */
  description?: string;
  /**
   * Name of the parent design object
   */
  parent_name?: string;
  [k: string]: unknown;
}
/**
 * References to GLTF node names
 */
export interface DesignNodeReference {
  /**
   * node reference of Faces mesh
   */
  faces?: string[];
  [k: string]: unknown;
}
/**
 * Aggregate metrics for this design model (centre of gravity, object counts). Computed at bake time so the viewer can show per-model info without reloading source.
 */
export interface DesignStats {
  cog_volume?: COG1;
  cog_mass?: COG2;
  /**
   * Number of physical objects per type, keyed by lowercase class name (e.g. beam, plate, shape, pipe, wall).
   */
  object_counts?: {
    [k: string]: number;
  };
  [k: string]: unknown;
}
/**
 * Volume-weighted centroid. Populated whenever any geometry contributes a non-zero volume.
 */
export interface COG1 {
  x: number;
  y: number;
  z: number;
  /**
   * Sum of contributing masses.
   */
  total_mass?: number;
  /**
   * Sum of contributing volumes.
   */
  total_volume?: number;
  [k: string]: unknown;
}
/**
 * Mass-weighted centroid. Only populated when every physical object has a material density defined.
 */
export interface COG2 {
  x: number;
  y: number;
  z: number;
  /**
   * Sum of contributing masses.
   */
  total_mass?: number;
  /**
   * Sum of contributing volumes.
   */
  total_volume?: number;
  [k: string]: unknown;
}
/**
 * Spec lineage + member roster for one ada.Connection Part inside this design model. Names are the same identifiers used as keys in object_metadata / object_guids on this DesignDataExtension, so the inspector joins by name with no extra lookups.
 */
export interface ConnectionInfo {
  /**
   * The Connection Part's name — used as a stable id when the inspector cross-links from a member back to its parent connection.
   */
  name: string;
  /**
   * Registered ConnectionSpec name (e.g. 'box.box_to_box') when the Connection was built from one. Absent on ad-hoc Connections.
   */
  spec_name?: string;
  /**
   * The build_component inputs dict the spec was evaluated with (per-role sections, angles, etc.). Absent when the Connection isn't spec-derived.
   */
  spec_inputs?: {
    [k: string]: unknown;
  };
  /**
   * Map of role name ('incoming', 'landing', ...) to member node names — lets the inspector show 'incoming: <beam>' rows that select the right member.
   */
  member_roles?: {
    [k: string]: string[];
  };
  /**
   * All beam member names this Connection groups (including any roles).
   */
  beam_names?: string[];
  /**
   * Stiffener plate names this Connection contributes.
   */
  plate_names?: string[];
  /**
   * Weld names this Connection owns. The inspector renders one 'select all welds (N)' link rather than the per-weld dump.
   */
  weld_names?: string[];
  [k: string]: unknown;
}
