# automatically generated by the FlatBuffers compiler, do not modify

# namespace: scene

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class Scene(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Scene()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScene(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # Scene
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Scene
    def Operation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Scene
    def CameraParams(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ada.comms.fb.scene.CameraParams import CameraParams

            obj = CameraParams()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Scene
    def CurrentFile(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ada.comms.fb.base.FileObject import FileObject

            obj = FileObject()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def SceneStart(builder):
    builder.StartObject(3)


def Start(builder):
    SceneStart(builder)


def SceneAddOperation(builder, operation):
    builder.PrependInt8Slot(0, operation, 0)


def AddOperation(builder, operation):
    SceneAddOperation(builder, operation)


def SceneAddCameraParams(builder, cameraParams):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(cameraParams), 0)


def AddCameraParams(builder, cameraParams):
    SceneAddCameraParams(builder, cameraParams)


def SceneAddCurrentFile(builder, currentFile):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(currentFile), 0)


def AddCurrentFile(builder, currentFile):
    SceneAddCurrentFile(builder, currentFile)


def SceneEnd(builder):
    return builder.EndObject()


def End(builder):
    return SceneEnd(builder)
