import {describe, it} from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {fileURLToPath} from "node:url";
import path from "node:path";

import {
    BEAM_COMPACT_BEAM_BYTES,
    BEAM_COMPACT_HEADER_BYTES,
    parseBeamSolidsCompact,
} from "../../services/feaBeamSolidsCompact";

// The AFBS expansion has a Python twin (`beam_compact.expand_beam_solid_instances`)
// and the two have to agree exactly, or a beam's vertices land somewhere
// different depending on which side drew them. So the main test here is not a
// hand-written expectation: it is a fixture the Python expander produced,
// committed next to this file and regenerated by
// `tools/gen_beam_solids_compact_fixture.py` (a pytest asserts it is current).

const FIXTURE_DIR = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "..",
    "fixtures",
    "beam_solids_compact",
);

function readFixtureBytes(name: string): ArrayBuffer {
    const buf = readFileSync(path.join(FIXTURE_DIR, name));
    // Node hands back a Buffer that is usually a window onto a shared pool, so
    // copy into an ArrayBuffer of exactly the right length — the parser takes
    // typed-array views at 4-byte offsets from the start of the buffer.
    return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

interface ExpectedFixture {
    mainPositions: number[];
    nVerts: number;
    positions: number[];
    indices: number[];
    drawRanges: {label: number; triStart: number; triCount: number}[];
    node0: number[];
    node1: number[];
    t: number[];
}

function readExpected(): ExpectedFixture {
    return JSON.parse(readFileSync(path.join(FIXTURE_DIR, "two_beams.expected.json"), "utf-8"));
}

/** Minimal AFBS builder for the negative cases and the hand-built beam. */
function buildAfbs(opts: {
    sections: {points: number[]; tris: number[]}[];
    beams: {
        label: number;
        section: number;
        node0: number;
        node1: number;
        origin: [number, number, number];
        xvec: [number, number, number];
        yvec: [number, number, number];
        length: number;
    }[];
    magic?: string;
    version?: number;
}): ArrayBuffer {
    const {sections, beams} = opts;
    let size = BEAM_COMPACT_HEADER_BYTES;
    for (const s of sections) size += 8 + s.points.length * 4 + s.tris.length * 4;
    size += beams.length * BEAM_COMPACT_BEAM_BYTES;

    const buf = new ArrayBuffer(size);
    const dv = new DataView(buf);
    const magic = opts.magic ?? "AFBS";
    for (let i = 0; i < 4; i++) dv.setUint8(i, magic.charCodeAt(i));
    dv.setUint32(4, opts.version ?? 1, true);
    dv.setUint32(8, sections.length, true);
    dv.setUint32(12, beams.length, true);

    let off = BEAM_COMPACT_HEADER_BYTES;
    for (const s of sections) {
        dv.setUint32(off, s.points.length / 2, true);
        dv.setUint32(off + 4, s.tris.length / 3, true);
        off += 8;
        for (const v of s.points) {
            dv.setFloat32(off, v, true);
            off += 4;
        }
        for (const v of s.tris) {
            dv.setUint32(off, v, true);
            off += 4;
        }
    }
    for (const b of beams) {
        dv.setUint32(off, b.label, true);
        dv.setUint32(off + 4, b.section, true);
        dv.setUint32(off + 8, b.node0, true);
        dv.setUint32(off + 12, b.node1, true);
        let p = off + 16;
        for (const v of [...b.origin, ...b.xvec, ...b.yvec, b.length]) {
            dv.setFloat32(p, v, true);
            p += 4;
        }
        off += BEAM_COMPACT_BEAM_BYTES;
    }
    return buf;
}

describe("parseBeamSolidsCompact", () => {
    it("reads the section table and the per-beam frames out of the Python fixture", () => {
        const parsed = parseBeamSolidsCompact(readFixtureBytes("two_beams.bin"));
        assert.equal(parsed.nBeams, 2);
        assert.equal(parsed.sections.length, 2);
        // A 4-point rectangle and a 3-point triangle: 2 × (points + 2 caps)
        // triangles each, and 2 rings of vertices per beam.
        assert.deepEqual(parsed.sections.map((s) => s.nPoints), [4, 3]);
        assert.deepEqual(Array.from(parsed.label), [101, 202]);
        assert.deepEqual(Array.from(parsed.section), [0, 1]);
        assert.deepEqual(Array.from(parsed.node0), [0, 2]);
        assert.deepEqual(Array.from(parsed.node1), [1, 3]);
        assert.equal(parsed.nVerts, 2 * 4 + 2 * 3);
        assert.equal(
            parsed.nTriangles,
            parsed.sections[0].nTriangles + parsed.sections[1].nTriangles,
        );
    });

    it("rejects a foreign magic", () => {
        const buf = buildAfbs({sections: [], beams: [], magic: "AFBV"});
        assert.throws(() => parseBeamSolidsCompact(buf), /bad magic/);
    });

    it("rejects a version it does not implement", () => {
        const buf = buildAfbs({sections: [], beams: [], version: 2});
        assert.throws(() => parseBeamSolidsCompact(buf), /version 2, expected 1/);
    });

    it("rejects a header-sized sliver", () => {
        assert.throws(() => parseBeamSolidsCompact(new ArrayBuffer(8)), /too small/);
    });

    it("rejects a file whose beam table was cut short", () => {
        const full = readFixtureBytes("two_beams.bin");
        const cut = full.slice(0, full.byteLength - BEAM_COMPACT_BEAM_BYTES);
        assert.throws(() => parseBeamSolidsCompact(cut), /beam table wants/);
    });

    it("rejects a file whose section payload was cut short", () => {
        const full = readFixtureBytes("two_beams.bin");
        const cut = full.slice(0, BEAM_COMPACT_HEADER_BYTES + 12);
        assert.throws(() => parseBeamSolidsCompact(cut), /truncated payload/);
    });

    it("rejects a beam pointing at a section that is not there", () => {
        const buf = buildAfbs({
            sections: [{points: [0, 0, 1, 0, 1, 1], tris: [0, 1, 2]}],
            beams: [{
                label: 1, section: 3, node0: 0, node1: 1,
                origin: [0, 0, 0], xvec: [1, 0, 0], yvec: [0, 1, 0], length: 1,
            }],
        });
        assert.throws(() => parseBeamSolidsCompact(buf), /references section 3 of 1/);
    });
});

// The expansion itself is no longer TypeScript: it is adacpp.cad.expand_beam_solids,
// compiled to wasm, and the four cases that used to live here moved with it --
// reproducing the reference buffers, draw ranges tiling the index buffer in record
// order, t varying around a ring on an eccentric beam, and t collapsing to zero on a
// zero-length element are all covered in adacpp's tests/ngeom/test_extrude.cpp and
// tests/py/test_extrude_sections.py.
//
// Testing it from here would mean loading a wasm module that only exists inside the
// deploy image, and a stub of it would test the stub. What IS still TypeScript is the
// AFBS parser above, and that is what this file covers.
