# automatically generated by the FlatBuffers compiler, do not modify

# namespace: base


class ParameterType(object):
    UNKNOWN = 0
    STRING = 1
    FLOAT = 2
    INTEGER = 3
    BOOLEAN = 4
    ARRAY = 6
