[procedures]
script_dir = "./scripts"
use_ifc_convert = false

[websockets]
server_temp_dir = "./server_temp"
external_files_dirs = ["./external_files"]
auto_load_temp_files = true

[ifc]
import_shape_geom = true