{% set data = load_setup_py_data() %}


package:
  name: ada-py
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
  run:
    - python
    - ifcopenshell
    - pythonocc-core
    - python-gmsh >=4.9.3
    - occt ==7.5.3
    - meshio[all]
    - pyquaternion
    - pytexit
    - jupyterlab
    - pythreejs
    - pyparsing
    - plotly
    - python-kaleido


test:
  source_files:
    - tests
    - files
  requires:
    - pytest
  imports:
    - ada

about:
  home: https://github.com/krande/adapy
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://adapy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - Krande
