{ % set data = load_setup_py_data() % }
  { % set version = data.get('version') % }

package:
  name: ada-py-packages
  version: { { version } }

source:
  path: ../

build:
  number: 0

outputs:
  - name: ada-py-core
    build:
      noarch: python
      number: 0
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - numpy
        - h5py
        - ifcopenshell
        - pythonocc-core
        - python-gmsh
        - pyquaternion
        - trimesh
        - meshio
        - pytexit
        - plotly

  - name: ada-py
    requirements:
      run:
        - { { pin_subpackage("ada-py-core", max_pin="x.x.x") } }
        - python-kaleido
        - jupyterlab
        - pythreejs
        - pyparsing
        - calculix

  - name: ada-py-test
    requirements:
      run:
        - { { pin_subpackage("ada-py", max_pin="x.x.x") } }
        - pytest
        - pytest-cov
    test:
      source_files:
        - tests
        - files
        - examples
      commands:
        - cd tests && pytest .

  - name: ada-py-core-test
    requirements:
      run:
        - { { pin_subpackage("ada-py-core", max_pin="x.x.x") } }
        - pytest
        - pytest-cov
    test:
      source_files:
        - tests
        - files
        - examples
      commands:
        - cd tests && pytest .

  - name: ada-py-whl
    type: wheel
    requirements:
      run:
        - { { pin_subpackage("ada-py", max_pin="x.x.x") } }


about:
  home: https://github.com/krande/adapy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
