{% set name = 'ada-py' %}
{% set data = load_setup_py_data() %}
{% set version = load_file_data('pyproject.toml')["project"]["version"] %}

{% set build = 0 %}
{% set test_ignores = '' %}

{% if variant == "core" %}
  {% set build = build + 100 %}
  {% set test_ignores = " --ignore=tests/full" %}
{% else %}
  {% set build = build + 200 %}
  {% set test_ignores = "" %}
{% endif %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: python -m pip install . --no-deps -vv
  number: {{ build }}
  string: {{ variant }}_h{{ PKG_HASH }}_{{ build }}
  entry_points:
    - ada-viewer=ada.visit.render_pygfx:main
  ignore_files:
    - node_modules/**/*
    - src/frontend/**/*
    - docs/**/*
    - examples/**/*
    - images/**/*
    - .github/**/*

# Set list of core dependencies (core -> conversion and analysis)
{% set core_deps = load_file_data('conda/environment.core.yml')['dependencies'] %}

# Maybe pytexit, plotly and python-kaleido should be moved to the "full" dependencies list

# Set full list of dependencies
{% set full_deps = core_deps + load_file_data('conda/environment.full.yml')['dependencies'] %}

{% set deps = core_deps if variant == "core" else full_deps %}

requirements:
  host:
    - python
  run:
    - python
    - kaleido-core 0.1.0
  {% for dep in deps %}
    - {{ dep }}
  {% endfor %}

test:
  source_files:
    - tests
    - files
    - examples
  requires:
    - pytest
    - pytest-cov
  imports:
    - ada
  commands:
    - pytest tests --ignore=tests/fem{{ test_ignores }} --cov=ada --cov-report=xml

about:
  home: https://github.com/krande/adapy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
