{% set data = load_setup_py_data() %}


package:
  name: ada-py
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - ifcopenshell
    - pythonocc-core
    - occt
    - python-gmsh
    - pyquaternion
    - trimesh
    - pytexit
    - jupyterlab
    - pythreejs
    - pyparsing
    - h5py
    - plotly
    - python-kaleido
    - meshio

# Dependencies that are currently left out
#    - numpy
#    - vtk
#    - toolz
#    - lmfit
#    - ccx2paraview
#    - ipygany
#    - pydantic
#    - pyvista
test:
  source_files:
    - tests
    - files
    - examples
  requires:
    - pytest
    - pytest-cov
  imports:
    - ada

about:
  home: https://github.com/krande/adapy
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
