{% set data = load_setup_py_data() %}


package:
  name: ada-py-core
  version: {{ data.get('version') }}

source:
  path: ../

build:
  #  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  include_recipe: False

requirements:
  build:
    - python
    - wheel
  run:
    - python
    - numpy
    - h5py
    - ifcopenshell
    - pythonocc-core
    - python-gmsh
    - pyquaternion
    - trimesh
    - meshio
    - calculix


outputs:
  - name: ada-py
    version: {{ data.get('version') }}
    requirements:
      host:
        - python
      run:
        - ada-py-core
        - plotly
        - python-kaleido
        - jupyterlab
        - pythreejs
        - pytexit
        - pyparsing
  - name: ada-py-test
    version: {{ data.get('version') }}
    requirements:
      host:
        - python
      run:
        - ada-py
    test:
      source_files:
        - tests
        - files
        - examples
      requires:
        - pytest
        - pytest-cov
      imports:
        - ada
  - name: ada-py-whl
    version: {{ data.get('version') }}
    type: wheel
    requirements:
      host:
        - python
      run:
        - ada-py


about:
  home: https://github.com/krande/adapy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
