{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: ada-py-packages
  version: {{ version }}

source:
  path: ../

build:
  number: 0

outputs:
  - name: ada-py-core
    build:
      noarch: python
      number: 0
      script: python -m pip install . --no-deps -vv
    include_recipe: False
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - numpy
        - h5py
        - ifcopenshell
        - pythonocc-core
        - python-gmsh
        - pyquaternion
        - trimesh
        - meshio

  - name: ada-py
    build:
      noarch: python
      skip: true  # [build_platform != target_platform]
    requirements:
      run:
        - {{ pin_subpackage("ada-py-core", max_pin="x.x.x") }}
        - plotly
        - python-kaleido
        - jupyterlab
        - pythreejs
        - pytexit
        - pyparsing
        - calculix

  - name: ada-py-core-test
    build:
      noarch: python
      skip: true  # [build_platform != target_platform]
    requirements:
      run:
        - {{ pin_subpackage("ada-py-core", max_pin="x.x.x") }}
    test:
      source_files:
        - conda/run_test.sh
        - conda/run_test.bat
        - tests
        - files
        - examples
      requires:
        - pytest
        - pytest-cov
      commands:
        - run_test.bat # [win]
        - run_test.sh # [not win]

  - name: ada-py-test
    build:
      noarch: python
      skip: true
    requirements:
      run:
        - {{ pin_subpackage("ada-py", max_pin="x.x.x") }}
    test:
      source_files:
        - conda/run_test.sh
        - conda/run_test.bat
        - tests
        - files
        - examples
      requires:
        - pytest
        - pytest-cov
      commands:
        - run_test.bat # [win]
        - run_test.sh # [not win]

  - name: ada-py-whl
    build:
      noarch: python
      skip: true  # [build_platform != target_platform]
    type: wheel
    requirements:
      run:
        - {{ pin_subpackage("ada-py", max_pin="x.x.x") }}


about:
  home: https://github.com/krande/adapy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
