{% set data = load_setup_py_data() %}


package:
  name: ada-py
  version: {{ data.get('version') }}

source:
  path: ../

build:
#  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  include_recipe: False

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - ifcopenshell
    - pythonocc-core
    - python-gmsh
    - pyquaternion
    - trimesh
    - jupyterlab
    - pyparsing
    - h5py
    - plotly
    - python-kaleido
    - meshio
    - pythreejs
    - pytexit
    - calculix

test:
  source_files:
    - tests
    - files
    - examples
  requires:
    - pytest
    - pytest-cov
  imports:
    - ada

about:
  home: https://github.com/krande/adapy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
