{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set name = 'undefined' %}
{% set test_ignores = '' %}

# Set name based on variant if else condition
{% if variant == "core" %}
  {% set name = "ada-py-core" %}
  {% set test_ignores = " --ignore=tests/full" %}
{% else %}
  {% set name = "ada-py" %}
  {% set test_ignores = "" %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps -vv

# Set list of core dependencies
{% set core_deps = [
    "numpy",
    "h5py",
    "ifcopenshell",
    "pythonocc-core",
    "python-gmsh",
    "pyquaternion",
    "trimesh",
    "send2trash",
    "meshio",
    "pytexit",
    "plotly"
] %}

# Set full list of dependencies
{% set full_deps = core_deps + [
    "python-kaleido",
    "jupyterlab",
    "pythreejs",
    "pyparsing",
    "calculix",
] %}

{% set deps = core_deps if variant == "core" else full_deps %}

requirements:
  host:
    - python
  run:
    - python
  {% for dep in deps %}
    - {{ dep }}
  {% endfor %}

test:
  requires:
    - pytest
    - pytest-cov
  imports:
    - ada
  source_files:
    - tests
    - files
    - examples
  commands:
    - pytest tests --ignore=tests/docker{{ test_ignores }} --cov=ada --cov-report=xml


about:
  home: https://github.com/krande/adapy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
