{% set data = load_setup_py_data() %}


package:
  name: ada-py
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.9
  run:
    - python >=3.9
    - numpy
    - ifcopenshell
    - pythonocc-core
    - python-gmsh
    - pyquaternion
    - trimesh
    - jupyterlab
    - pyparsing
    - h5py
    - plotly
    - python-kaleido
    - meshio
    - pythreejs
  run_constrained:
    - pytexit

test:
  source_files:
    - tests
    - files
    - examples
  requires:
    - pytest
    - pytest-cov
  imports:
    - ada

about:
  home: https://github.com/krande/adapy
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
