{% set data = load_setup_py_data() %}

package:
  name: ada-py
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - ifcopenshell
    - pythonocc-core
    - gmsh
    - vtk
    - meshio[all]
    - toolz
    - lmfit
    - pyquaternion
    - ccx2paraview
    - pytexit
    - jupyterlab
    - pythreejs
    - pyparsing
    - plotly
    - python-kaleido
    - ipygany
    - pydantic
    - pyvista


test:
  source_files:
    - tests
    - files
  requires:
    - pytest
  imports:
    - ada

about:
  home: https://github.com/krande/adapy
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "A python library for structural analysis and design"
  doc_url: https://adapy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - Krande
