"""Abaqus/CAE output: a script that rebuilds a concept model as editable geometry.

Entry point: :meth:`ada.Part.to_abaqus_cae_script`, which delegates to
:func:`ada.cadit.cae.writer.write_cae_script`.

The model's supports, loads and analysis steps come along with the geometry;
:mod:`ada.cadit.cae.analysis` is where the two stores adapy keeps them in are described, and
which of them is read.
"""

from .analysis import (
    CARRIED_BC_TYPES,
    CARRIED_ELEMENT_TYPES,
    CARRIED_LOAD_TYPES,
    CARRIED_SHELL_ELEMENT_TYPES,
    REFUSED_BC_TYPES,
    REFUSED_LOAD_TYPES,
    AnalysisNotSupported,
    AnalysisPlan,
    BcPlan,
    LoadPlan,
    RegionPlan,
    StepPlan,
    analysis_fems,
    check_element_type,
    check_shell_element_type,
    plan_analysis,
    refuse_untranslated_concept_analysis,
    vertex_index,
)
from .curves import (
    CURVE_LENGTH_REL_TOL,
    MAX_TURN_RADIANS,
    CurveNotSupported,
    is_curved_beam_type,
    sample_member_curve,
)
from .names import CaeNameError, NameRegistry, sanitise_cae_name
from .plates import (
    PLATE_AREA_REL_TOL,
    PLATE_NORMAL_TOL,
    STRINGER_MEASUREMENT,
    FaceLocator,
    PlateBody,
    PlateNotSupported,
    PlatePlan,
    check_no_nested_plates,
    interior_point_2d,
    plate_body,
    stringer_members,
)
from .topology import (
    CAE_MERGE_TOL,
    Crossing,
    PartTopology,
    Segment,
    distinct_points,
    expected_topology,
    find_crossings,
)
from .writer import (
    CURVE_N1_MIN_SIN,
    CURVED_BEAM_TYPES,
    EQUILIBRIUM_ABS_FLOOR,
    EQUILIBRIUM_REL_TOL,
    FIELD_OUTPUT_REQUEST_NAME,
    FIELD_OUTPUT_VARIABLES,
    REFUSED_BEAM_TYPES,
    SOLVER_SUCCESS_MARKER,
    CaeWriteError,
    SkippedObject,
    UnsupportedBeamError,
    beam_endpoints,
    beam_n1,
    beam_section_offset,
    build_plan,
    check_beam_shape,
    check_mesh_and_job,
    check_n1_holds_along_the_curve,
    check_unit_scale,
    render_script,
    write_cae_script,
)

__all__ = [
    "STRINGER_MEASUREMENT",
    "CAE_MERGE_TOL",
    "CARRIED_BC_TYPES",
    "CARRIED_ELEMENT_TYPES",
    "CARRIED_LOAD_TYPES",
    "CARRIED_SHELL_ELEMENT_TYPES",
    "CURVED_BEAM_TYPES",
    "CURVE_LENGTH_REL_TOL",
    "CURVE_N1_MIN_SIN",
    "EQUILIBRIUM_ABS_FLOOR",
    "EQUILIBRIUM_REL_TOL",
    "FIELD_OUTPUT_REQUEST_NAME",
    "FIELD_OUTPUT_VARIABLES",
    "MAX_TURN_RADIANS",
    "PLATE_AREA_REL_TOL",
    "PLATE_NORMAL_TOL",
    "REFUSED_BC_TYPES",
    "REFUSED_BEAM_TYPES",
    "REFUSED_LOAD_TYPES",
    "SOLVER_SUCCESS_MARKER",
    "AnalysisNotSupported",
    "AnalysisPlan",
    "BcPlan",
    "CaeNameError",
    "CaeWriteError",
    "Crossing",
    "CurveNotSupported",
    "FaceLocator",
    "LoadPlan",
    "NameRegistry",
    "PartTopology",
    "PlateBody",
    "PlateNotSupported",
    "PlatePlan",
    "RegionPlan",
    "Segment",
    "SkippedObject",
    "StepPlan",
    "UnsupportedBeamError",
    "analysis_fems",
    "beam_endpoints",
    "beam_n1",
    "beam_section_offset",
    "build_plan",
    "check_beam_shape",
    "check_element_type",
    "check_mesh_and_job",
    "check_n1_holds_along_the_curve",
    "stringer_members",
    "check_no_nested_plates",
    "check_shell_element_type",
    "check_unit_scale",
    "distinct_points",
    "expected_topology",
    "find_crossings",
    "interior_point_2d",
    "is_curved_beam_type",
    "plan_analysis",
    "plate_body",
    "refuse_untranslated_concept_analysis",
    "render_script",
    "sample_member_curve",
    "sanitise_cae_name",
    "vertex_index",
    "write_cae_script",
]
