// AFBS (Adapy Field Beam Solids) compact beam-solid artefact: parser and expander.
//
// The beam-solid mesh used to arrive as a GLB plus an AFBV warp sidecar — on a
// large deck 88 MB of vertex buffer and 32 MB of per-vertex warp records, all
// of it derivable. Every beam is one section outline swept between two points,
// and a deck of 165k beams has on the order of ten distinct outlines. AFBS
// ships those outlines once plus a 56-byte frame per beam; this module turns
// them back into exactly the buffers the GLB path produced, so everything
// downstream (draw ranges, picking, element-field paint, warp, visibility)
// sees no difference at all.
//
// Format, little-endian and 4-byte aligned throughout — mirrors
// ``ada.fem.results.artefacts.formats``:
//
//   bytes  content
//   0..3   magic = "AFBS"
//   4..7   uint32 version (=1)
//   8..11  uint32 n_sections
//   12..15 uint32 n_beams
//   16..   n_sections × (uint32 n_points, uint32 n_tris,
//                        float32 points[n_points × 2],
//                        uint32  tris[n_tris × 3])
//   ...    n_beams × 56 bytes (uint32 label, section, node0, node1,
//                              float32 origin[3], xvec[3], yvec[3], length)
//
// The arithmetic in `expandBeamSolids` is written to reproduce the Python
// reference (`beam_compact.expand_beam_solid_instances`) bit for bit: the same
// operations in the same order, float64 throughout, rounded to float32 only
// where the output array is float32. A committed fixture generated by the
// Python side is the test for that.

import type {FeaFetcher} from "./fea/feaFetcher";

import {loadEmscriptenModule} from "@/utils/wasm/emscriptenLoader";

const WASM_URL = "/wasm/adacpp_extrude.js";

/** The embind surface of adacpp_extrude. Positional names in the generated
 *  .d.ts carry no meaning, so the shape is stated here instead. */
interface AdacppExtrude {
    expandBeamSolids(
        sections: {points: Float64Array; triangles: Uint32Array}[],
        instances: {
            label: Uint32Array;
            section: Uint32Array;
            node0: Uint32Array;
            node1: Uint32Array;
            origin: Float64Array;
            xvec: Float64Array;
            yvec: Float64Array;
            length: Float64Array;
        },
        points: Float64Array,
    ): {
        positions: Float32Array;
        indices: Uint32Array;
        node0: Uint32Array;
        node1: Uint32Array;
        t: Float32Array;
        rangeLabel: Uint32Array;
        rangeTriStart: Uint32Array;
        rangeTriCount: Uint32Array;
    };
}

const BEAM_COMPACT_MAGIC = 0x53424641; // "AFBS" little-endian
export const BEAM_COMPACT_HEADER_BYTES = 16;
export const BEAM_COMPACT_BEAM_BYTES = 56;
export const BEAM_COMPACT_VERSION = 1;

// The beam record read as uint32 words; the float fields are the same words
// reinterpreted. Kept as named offsets so the layout lives in one place.
const BEAM_WORDS = BEAM_COMPACT_BEAM_BYTES / 4; // 14

export interface CompactSectionOutline {
    /** Outline sample count. The extrusion has 2 × this many vertices:
     *  point k is vertex k at the near end and k + nPoints at the far end. */
    nPoints: number;
    nTriangles: number;
    /** (u, v) pairs in the profile plane, length nPoints × 2. */
    points: Float32Array;
    /** Triangle corners into the 2 × nPoints extruded vertices, length
     *  nTriangles × 3. Side quads then both caps, wound outward. */
    triangles: Uint32Array;
}

export interface ParsedBeamSolidsCompact {
    sections: CompactSectionOutline[];
    nBeams: number;
    /** Source line-element label per beam — the AFEM/draw-range key. */
    label: Uint32Array;
    /** Index into `sections` per beam. */
    section: Uint32Array;
    /** Parent line element's endpoint nodes, as rows of the main mesh's
     *  point buffer. Per beam: every vertex it owns carries the same pair. */
    node0: Uint32Array;
    node1: Uint32Array;
    /** BeamFrame, flattened 3 floats per beam. `up` is not stored — it is
     *  normalize(cross(xvec, yvec)) by construction. */
    origin: Float32Array;
    xvec: Float32Array;
    yvec: Float32Array;
    length: Float32Array;
    /** What the expansion will produce, so a caller can size buffers or
     *  cross-check the manifest before doing the work. */
    nVerts: number;
    nTriangles: number;
}

export interface ExpandedBeamSolids {
    positions: Float32Array; // nVerts × 3
    indices: Uint32Array; // nTriangles × 3
    nVerts: number;
    // Per-beam draw ranges, split into three parallel arrays rather than an
    // array of objects so the whole result transfers out of the worker
    // instead of being structured-cloned object by object.
    elemLabel: Uint32Array;
    elemTriStart: Uint32Array; // in triangles, like AFEM
    elemTriCount: Uint32Array;
    // The AFBV triple, recomputed per vertex. Same shape as
    // ParsedBeamSolidsWarp so the warp installer takes it unchanged.
    node0: Uint32Array;
    node1: Uint32Array;
    t: Float32Array;
}

export function parseBeamSolidsCompact(buf: ArrayBuffer): ParsedBeamSolidsCompact {
    if (buf.byteLength < BEAM_COMPACT_HEADER_BYTES) {
        throw new Error(`beam-solid compact: too small (${buf.byteLength} bytes)`);
    }
    const dv = new DataView(buf);
    const magic = dv.getUint32(0, true);
    if (magic !== BEAM_COMPACT_MAGIC) {
        throw new Error(`beam-solid compact: bad magic 0x${magic.toString(16)}`);
    }
    const version = dv.getUint32(4, true);
    if (version !== BEAM_COMPACT_VERSION) {
        throw new Error(
            `beam-solid compact: version ${version}, expected ${BEAM_COMPACT_VERSION}`,
        );
    }
    const nSections = dv.getUint32(8, true);
    const nBeams = dv.getUint32(12, true);

    const sections: CompactSectionOutline[] = new Array(nSections);
    let cursor = BEAM_COMPACT_HEADER_BYTES;
    for (let s = 0; s < nSections; s++) {
        if (cursor + 8 > buf.byteLength) {
            throw new Error(`beam-solid compact: truncated header of section ${s}`);
        }
        const nPoints = dv.getUint32(cursor, true);
        const nTriangles = dv.getUint32(cursor + 4, true);
        cursor += 8;
        const ptsBytes = nPoints * 2 * 4;
        const triBytes = nTriangles * 3 * 4;
        if (cursor + ptsBytes + triBytes > buf.byteLength) {
            throw new Error(`beam-solid compact: truncated payload of section ${s}`);
        }
        // Views, not copies: every offset is a multiple of 4 by construction,
        // and the caller (the worker) owns the buffer for the expansion's life.
        const points = new Float32Array(buf, cursor, nPoints * 2);
        cursor += ptsBytes;
        const triangles = new Uint32Array(buf, cursor, nTriangles * 3);
        cursor += triBytes;
        sections[s] = {nPoints, nTriangles, points, triangles};
    }

    if (cursor + nBeams * BEAM_COMPACT_BEAM_BYTES > buf.byteLength) {
        throw new Error(
            `beam-solid compact: beam table wants ${nBeams * BEAM_COMPACT_BEAM_BYTES} bytes, ` +
            `${buf.byteLength - cursor} left`,
        );
    }
    const words = new Uint32Array(buf, cursor, nBeams * BEAM_WORDS);
    const floats = new Float32Array(buf, cursor, nBeams * BEAM_WORDS);

    const label = new Uint32Array(nBeams);
    const section = new Uint32Array(nBeams);
    const node0 = new Uint32Array(nBeams);
    const node1 = new Uint32Array(nBeams);
    const origin = new Float32Array(nBeams * 3);
    const xvec = new Float32Array(nBeams * 3);
    const yvec = new Float32Array(nBeams * 3);
    const length = new Float32Array(nBeams);

    let nVerts = 0;
    let nTriangles = 0;
    for (let b = 0; b < nBeams; b++) {
        const w = b * BEAM_WORDS;
        const sIdx = words[w + 1];
        if (sIdx >= nSections) {
            throw new Error(`beam-solid compact: beam ${b} references section ${sIdx} of ${nSections}`);
        }
        label[b] = words[w];
        section[b] = sIdx;
        node0[b] = words[w + 2];
        node1[b] = words[w + 3];
        const o = b * 3;
        origin[o] = floats[w + 4];
        origin[o + 1] = floats[w + 5];
        origin[o + 2] = floats[w + 6];
        xvec[o] = floats[w + 7];
        xvec[o + 1] = floats[w + 8];
        xvec[o + 2] = floats[w + 9];
        yvec[o] = floats[w + 10];
        yvec[o + 1] = floats[w + 11];
        yvec[o + 2] = floats[w + 12];
        length[b] = floats[w + 13];
        nVerts += 2 * sections[sIdx].nPoints;
        nTriangles += sections[sIdx].nTriangles;
    }

    return {
        sections, nBeams, label, section, node0, node1,
        origin, xvec, yvec, length, nVerts, nTriangles,
    };
}

/** Sweep every beam's outline along its frame, exactly as the bake's
 *  procedural extruder does, and rebuild the per-vertex warp mapping.
 *
 *  `mainPositions` is the main FEA mesh's position buffer — `node0` / `node1`
 *  index it. The axial parameter `t` is measured against those NODE positions
 *  rather than against the extrusion axis: an eccentric beam (different
 *  offsets at its two ends) has a frame axis that is not the element axis, so
 *  `t` is not constant around a ring and cannot be shipped per section. */
/** Expand the parsed artefact into mesh buffers, through the same C++ the bake
 *  sweeps its sections with (`adacpp.cad.expand_beam_solids`, built to wasm).
 *
 *  This used to be a hand-written transcription of the Python reference
 *  expander, the two kept agreeing by a committed fixture and by writing each
 *  "the way the other would do it". One formula, three implementations. Now the
 *  formula lives once and this marshals into it.
 *
 *  Worker-only: the module is an ES6 emscripten factory served from /wasm. */
export async function expandBeamSolids(
    parsed: ParsedBeamSolidsCompact,
    mainPositions: Float32Array,
): Promise<ExpandedBeamSolids> {
    const mod = await loadEmscriptenModule<AdacppExtrude>(WASM_URL);

    // embind takes plain typed arrays; the module reads f64 for anything
    // positional, so widen here rather than let it coerce element by element.
    const sections = parsed.sections.map((sec) => ({
        points: Float64Array.from(sec.points),
        triangles: sec.triangles,
    }));

    const out = mod.expandBeamSolids(
        sections,
        {
            label: parsed.label,
            section: parsed.section,
            node0: parsed.node0,
            node1: parsed.node1,
            origin: Float64Array.from(parsed.origin),
            xvec: Float64Array.from(parsed.xvec),
            yvec: Float64Array.from(parsed.yvec),
            length: Float64Array.from(parsed.length),
        },
        Float64Array.from(mainPositions),
    );

    return {
        positions: out.positions,
        indices: out.indices,
        nVerts: out.positions.length / 3,
        elemLabel: out.rangeLabel,
        elemTriStart: out.rangeTriStart,
        elemTriCount: out.rangeTriCount,
        node0: out.node0,
        node1: out.node1,
        t: out.t,
    };
}

/** Parse + expand in one call. The worker's entry point, and the main
 *  thread's fallback when no worker can be spawned — one function so the two
 *  cannot drift apart. */
export async function expandBeamSolidsFromBytes(
    compact: ArrayBuffer,
    mainPositions: Float32Array,
): Promise<ExpandedBeamSolids> {
    return expandBeamSolids(parseBeamSolidsCompact(compact), mainPositions);
}

/** Fetch the compact beam-solid artefact. `fetcher` resolves the
 *  manifest-relative filename to bytes; see `feaFetcher.ts`. Parsing is the
 *  caller's, because the raw bytes are what gets transferred to the worker. */
export async function fetchBeamSolidsCompact(
    fetcher: FeaFetcher,
    compactUrl: string,
): Promise<ArrayBuffer> {
    return fetcher(compactUrl);
}
