build:
	docker build ../ -t krande/ada:base -f base.Dockerfile

push:
	docker push krande/ada:base


bdev:
	docker build ../ -t krande/ada:dev -f dev.Dockerfile


bfem:
	docker build ../ -t krande/ada:femtests -f femtests.Dockerfile