"""Generate the adacpp C++ header for the ADA_EXT_data glTF extension from the JSON schema.

Single source of truth: ``src/gltf_extension_schema/design_and_analysis_extension.schema.json`` (the
same schema that drives the Pydantic + TS .d.ts codegen — see the ``json-code-gen-*`` pixi tasks).
This emits a lightweight, dependency-free C++ struct (no nlohmann/boost — adacpp hand-authors JSON)
plus a ``to_json()`` and a ``kSchemaVersion`` constant taken from the schema's ``version`` default, so
producer/consumer drift is a checkable VERSION mismatch rather than an unexpected loader crash.

The native STEP->GLB writer embeds the default (empty design/sim arrays, the schema version, null
assembly_guid) — a STEP import carries no adapy design/sim objects. The array item types stay opaque
(pre-serialized JSON strings) since the native path never populates them; the struct is still the
single typed place the extension is produced, generated from the schema.

Run via ``pixi run json-code-gen-cpp`` (writes into the sibling adacpp checkout); a drift test
(tests/core/cadit/step/test_ada_ext_codegen.py) fails if the schema version moves without regenerating.
"""

from __future__ import annotations

import json
import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent.parent
_SCHEMA = _HERE / "src" / "gltf_extension_schema" / "design_and_analysis_extension.schema.json"
_DEFAULT_OUT = _HERE.parent / "adacpp" / "src" / "geom" / "neutral" / "ada_ext_schema.h"


def _field(name: str, prop: dict) -> tuple[str, str]:
    """(C++ member declaration, to_json value expression) for one schema property.

    No trailing comments on members — clang-format aligns consecutive trailing comments, which would
    make the emitted header drift from a fresh generation (the drift test compares them byte-for-byte).
    """
    t = prop.get("type")
    if t == "array":
        return (f"    std::vector<std::string> {name};", f"arr({name})")
    if t == "string":
        default = prop.get("default")
        if default is None:
            return (f"    std::optional<std::string> {name};", f"opt({name})")
        return (f'    std::string {name} = "{default}";', f"str({name})")
    raise SystemExit(f"codegen_ada_ext_cpp: unsupported property type {t!r} for {name!r} — extend the generator")


def generate(schema_path: pathlib.Path) -> str:
    schema = json.loads(schema_path.read_text())
    props: dict = schema["properties"]
    version = props.get("version", {}).get("default", "0.0.0")
    title = schema.get("title", "ADA_EXT_data")

    decls: list[str] = []
    serial: list[str] = []
    for i, (name, prop) in enumerate(props.items()):
        decl, value = _field(name, prop)
        decls.append(decl)
        opener = "{" if i == 0 else ","
        serial.append(f'        o << "{opener}\\"{name}\\":" << {value};')

    fields = "\n".join(decls)
    body = "\n".join(serial)
    return f"""// GENERATED by scripts/codegen_ada_ext_cpp.py from
// design_and_analysis_extension.schema.json — DO NOT EDIT. Run `pixi run json-code-gen-cpp`.
// {title}; schema version {version}.
#pragma once

#include <optional>
#include <sstream>
#include <string>
#include <vector>

namespace adacpp::ada_ext {{

// Schema version this header was generated from. The producer stamps it into ADA_EXT_data.version so
// a consumer (viewer) / the drift test can detect a schema change as a version mismatch, not a crash.
inline constexpr const char *kSchemaVersion = "{version}";

// {title} (the glTF ``ADA_EXT_data`` extension). Default = a STEP import: empty design/sim
// arrays, the schema version, null assembly_guid. The design/simulation array items are opaque
// pre-serialized JSON strings (the native path never populates them) — push a serialized object.
struct AdaDesignAndAnalysisExtension {{
{fields}

    std::string to_json() const {{
        auto arr = [](const std::vector<std::string> &v) {{
            std::string s = "[";
            for (size_t i = 0; i < v.size(); ++i) {{
                if (i)
                    s += ",";
                s += v[i];
            }}
            return s + "]";
        }};
        auto str = [](const std::string &s) {{ return "\\"" + s + "\\""; }};
        auto opt = [](const std::optional<std::string> &o) {{ return o ? ("\\"" + *o + "\\"") : std::string("null"); }};
        std::ostringstream o;
{body}
        o << "}}";
        return o.str();
    }}
}};

}} // namespace adacpp::ada_ext
"""


def main() -> int:
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else _DEFAULT_OUT
    if not out.parent.is_dir():
        sys.stderr.write(f"codegen_ada_ext_cpp: output dir missing: {out.parent} (is adacpp a sibling checkout?)\n")
        return 2
    out.write_text(generate(_SCHEMA))
    version = json.loads(_SCHEMA.read_text())["properties"]["version"]["default"]
    print(f"wrote {out}  (schema version {version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
