"""Execute the docs notebooks and convert them to Markdown pages for the Zensical site.

Zensical runs no MkDocs plugins, so there is no mkdocs-jupyter / nbsphinx step: every
``docs/**/*.ipynb`` is rendered here to a ``<name>.md`` beside it (gitignored), which the
site then builds like any other page. The ``.ipynb`` itself is copied into the site as a
static file, so each page links to its source notebook for download.

The 3D viewer a ``.show()`` call leaves in a notebook is a plain ``text/html`` output: an
``<iframe srcdoc="...">`` holding the whole viewer app with the model's GLB inlined (~2 MB
each). Raw HTML passes through Markdown untouched, so it would stay interactive as it is,
but every viewer would then sit inline in its page. Instead each srcdoc is written out as
``<name>_files/viewer-<n>.html`` and the page gets a lazy ``<iframe src=...>``: the page
loads at once and each viewer only when scrolled to. The viewer app itself (~3 MB of JS and
CSS, identical in every viewer; only the inlined ``window.B64GLTF`` model differs) is moved
to ``docs/_static/notebook-viewer/`` under a content hash, so the site and the browser cache
hold it once.

Like nbsphinx's ``execute=auto``, a notebook is executed only if none of its code cells
carries outputs; ``--execute`` forces it, ``--no-execute`` never does. A cell that raises
fails the build.

The same viewer serves **3D figures** on ordinary Markdown pages. Each entry in ``FIGURES``
names a function in an example script that returns a model; a full run calls it and renders
it the way ``show()`` would, to ``docs/_static/viewer-figures/<name>.html`` (gitignored),
which the page embeds as a lazy ``<iframe>``.

    python scripts/docs_notebooks.py [--execute | --no-execute] [--clean] [paths...]
"""

from __future__ import annotations

import argparse
import hashlib
import html
import os
import pathlib
import re
import shutil
import sys

import nbformat
from nbconvert import MarkdownExporter
from nbconvert.preprocessors import ExecutePreprocessor

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
SHARED = DOCS / "_static" / "notebook-viewer"
FIGURES_DIR = DOCS / "_static" / "viewer-figures"
MARKER = "<!-- generated by scripts/docs_notebooks.py; edit the .ipynb instead -->"

#: Interactive 3D figures for Markdown pages: name -> "script.py:function" (relative to the repo
#: root). The function returns anything ``show()`` accepts; the page embeds
#: ``_static/viewer-figures/<name>.html``.
FIGURES = {
    "penetration_detail": "examples/penetration_detail.py:figure",
}

_SRCDOC = re.compile(r'<iframe\s+srcdoc="(?P<doc>[^"]*)"(?P<attrs>[^>]*)>\s*</iframe>', re.S)
_HEIGHT = re.compile(r'height="(\d+)(?:px)?"')
# The viewer bundle's app script and stylesheet. Both are far larger than anything else in
# the document; the tiny scripts that set the model and flags stay inline.
_APP_SCRIPT = re.compile(r'<script type="module" crossorigin>(?P<body>.*?)</script>', re.S)
_APP_STYLE = re.compile(r"<style>(?P<body>.*?)</style>", re.S)
_MIN_SHARED = 32_000


def share_viewer_assets(doc: str, viewer_dir: pathlib.Path) -> str:
    """Replace the inlined viewer app JS/CSS with references to content-hashed shared files."""

    def _write(body: str, suffix: str) -> str:
        digest = hashlib.sha256(body.encode("utf-8")).hexdigest()[:12]
        target = SHARED / f"viewer-{digest}{suffix}"
        if not target.exists():
            SHARED.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding="utf-8")
        return os.path.relpath(target, viewer_dir).replace(os.sep, "/")

    def _script(m: re.Match) -> str:
        if len(m["body"]) < _MIN_SHARED:
            return m[0]
        return f'<script type="module" crossorigin src="{_write(m["body"], ".js")}"></script>'

    def _style(m: re.Match) -> str:
        if len(m["body"]) < _MIN_SHARED:
            return m[0]
        return f'<link rel="stylesheet" href="{_write(m["body"], ".css")}">'

    doc = _APP_SCRIPT.sub(_script, doc, count=1)
    return _APP_STYLE.sub(_style, doc, count=1)


def find_notebooks(paths: list[str]) -> list[pathlib.Path]:
    roots = [pathlib.Path(p).resolve() for p in paths] or [DOCS]
    found: list[pathlib.Path] = []
    for root in roots:
        candidates = [root] if root.suffix == ".ipynb" else root.rglob("*.ipynb")
        found += [p for p in candidates if ".ipynb_checkpoints" not in p.parts]
    return sorted(set(found))


def has_outputs(nb) -> bool:
    return any(c.get("outputs") for c in nb.cells if c.cell_type == "code")


def execute(nb, cwd: pathlib.Path, timeout: int) -> None:
    ExecutePreprocessor(timeout=timeout, kernel_name="python3").preprocess(nb, {"metadata": {"path": str(cwd)}})


def extract_viewers(nb, files_dir: pathlib.Path) -> int:
    """Move every inline ``<iframe srcdoc>`` output to its own HTML file; return how many."""
    count = 0

    def _replace(match: re.Match) -> str:
        nonlocal count
        count += 1
        name = f"viewer-{count}.html"
        files_dir.mkdir(parents=True, exist_ok=True)
        doc = share_viewer_assets(html.unescape(match["doc"]), files_dir)
        (files_dir / name).write_text(doc, encoding="utf-8")
        height = _HEIGHT.search(match["attrs"])
        h = f"{height[1]}px" if height else "500px"
        return (
            f'<iframe class="ada-viewer" src="{files_dir.name}/{name}" loading="lazy" '
            f'style="width:100%;height:{h};border:none;" title="3D viewer"></iframe>'
        )

    for cell in nb.cells:
        for out in cell.get("outputs", []):
            data = out.get("data", {})
            text = data.get("text/html")
            if text is None:
                continue
            text = "".join(text) if isinstance(text, list) else text
            if "srcdoc=" in text:
                data["text/html"] = _SRCDOC.sub(_replace, text)
    return count


def to_markdown(nb, nb_path: pathlib.Path, files_dir: pathlib.Path) -> str:
    exporter = MarkdownExporter()
    body, resources = exporter.from_notebook_node(
        nb, resources={"output_files_dir": files_dir.name, "unique_key": nb_path.stem}
    )
    for rel, blob in resources.get("outputs", {}).items():
        target = nb_path.parent / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(blob)

    # Python-Markdown only passes raw HTML through when the block starts a line after a
    # blank one; nbconvert leaves some HTML outputs glued to the preceding text.
    body = re.sub(r"\n(?=<(?:div|iframe|table|svg)\b)", "\n\n", body)

    note = (
        f'!!! info "Notebook"\n'
        f"    This page was generated from "
        f"[`{nb_path.name}`]({nb_path.name}){{: download }}. "
        f"Download it to run the examples yourself.\n"
    )
    # Keep the notebook's own first heading as the page title, with the note under it.
    lines = body.lstrip().splitlines()
    if lines and lines[0].startswith("# "):
        return "\n".join([MARKER, "", lines[0], "", note, *lines[1:]]) + "\n"
    return "\n".join([MARKER, "", f"# {nb_path.stem.replace('_', ' ').title()}", "", note, body]) + "\n"


def convert(nb_path: pathlib.Path, mode: str, timeout: int) -> None:
    nb = nbformat.read(nb_path, as_version=4)
    run = mode == "always" or (mode == "auto" and not has_outputs(nb))
    if run:
        print(f"executing  {nb_path.relative_to(ROOT)}", flush=True)
        execute(nb, nb_path.parent, timeout)

    files_dir = nb_path.with_name(f"{nb_path.stem}_files")
    if files_dir.exists():
        shutil.rmtree(files_dir)
    viewers = extract_viewers(nb, files_dir)
    md = to_markdown(nb, nb_path, files_dir)
    nb_path.with_suffix(".md").write_text(md, encoding="utf-8")
    print(f"converted  {nb_path.relative_to(ROOT)} ({viewers} viewer(s))", flush=True)


def render_figure(name: str, spec: str) -> None:
    """Run ``script.py:function`` and write its model as a standalone viewer page."""
    import base64
    import runpy
    import tempfile

    from ada.visit.rendering.renderer_react import RendererReact

    script, func = spec.rsplit(":", 1)
    print(f"figure     {name} <- {spec}", flush=True)
    model = runpy.run_path(str(ROOT / script), run_name="docs_figure")[func]()
    # ``to_gltf`` rather than the GLB ``show()`` builds: ``show()``'s scene currently renders
    # every object in the default grey, and a figure is usually about the coloured detail.
    with tempfile.TemporaryDirectory() as tmp:
        glb = pathlib.Path(tmp) / f"{name}.glb"
        model.to_gltf(glb)
        encoded = base64.b64encode(glb.read_bytes()).decode("ascii")
    doc = RendererReact().get_html_with_injected_data(embed_base64_glb=encoded)
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    (FIGURES_DIR / f"{name}.html").write_text(share_viewer_assets(doc, FIGURES_DIR), encoding="utf-8")


def clean(notebooks: list[pathlib.Path]) -> None:
    for nb_path in notebooks:
        md = nb_path.with_suffix(".md")
        if md.exists() and md.read_text(encoding="utf-8").startswith(MARKER):
            md.unlink()
        shutil.rmtree(nb_path.with_name(f"{nb_path.stem}_files"), ignore_errors=True)
    shutil.rmtree(SHARED, ignore_errors=True)
    shutil.rmtree(FIGURES_DIR, ignore_errors=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--execute", dest="mode", action="store_const", const="always")
    group.add_argument("--no-execute", dest="mode", action="store_const", const="never")
    parser.add_argument("--clean", action="store_true", help="remove the generated pages and exit")
    parser.add_argument("--timeout", type=int, default=600, help="per-cell execution timeout in seconds")
    parser.add_argument("paths", nargs="*", help="notebooks or folders (default: docs/)")
    args = parser.parse_args(argv)

    notebooks = find_notebooks(args.paths)
    if args.clean:
        clean(notebooks)
        return 0
    if not args.paths:
        # A full run rewrites every viewer, so drop bundles left by older viewer builds.
        shutil.rmtree(SHARED, ignore_errors=True)
        shutil.rmtree(FIGURES_DIR, ignore_errors=True)
        for name, spec in FIGURES.items():
            render_figure(name, spec)
    for nb_path in notebooks:
        convert(nb_path, args.mode or "auto", args.timeout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
