# generated by datamodel-codegen:
#   filename:  design_and_analysis_extension.schema.json
#   timestamp: 2026-05-28T18:11:17+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field

from . import design_extension_schema, simulation_extension_schema


class ComponentInfo(BaseModel):
    type: str = Field(
        ...,
        description="Component category. Today only 'connection'; future component kinds (bolted joints, stiffener assemblies, ...) will use their own tags.",
    )
    spec_name: str = Field(..., description='Registered ConnectionSpec name this component was built from.')
    spec_inputs: Optional[Dict[str, Any]] = Field(
        None,
        description='Inputs (sections, angles, ...) the spec was evaluated with — the same dict shape build_component accepts.',
    )
    member_groups: Optional[Dict[str, List[str]]] = Field(
        None,
        description="Optional map of role name (e.g. 'incoming', 'landing') to member node names — lets the viewer highlight individual roles.",
    )


class AdaDesignAndAnalysisExtension(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    simulation_objects: Optional[List[simulation_extension_schema.SimulationDataExtensionMetadata]] = Field(
        [], description='Array containing Simulation Data objects'
    )
    design_objects: Optional[List[design_extension_schema.DesignDataExtension]] = Field(
        [], description='Array containing Design Data objects'
    )
    version: Optional[str] = Field('1.2.0', description='Version of the ADA GLTF extension schema')
    assembly_guid: Optional[str] = Field(
        None,
        description="Stable lineage anchor: the source Assembly's guid. CAD and FEA exports derived from the same Assembly share this value so a viewer can match them without name lookups.",
    )
    component_info: Optional[ComponentInfo] = Field(
        None,
        description='Present when the GLB represents a single Connection component built from a registered ConnectionSpec. Lets the viewer show the spec lineage and bind re-build UI back to the source registry.',
    )
