# generated by datamodel-codegen:
#   filename:  design_and_analysis_extension.schema.json
#   timestamp: 2025-06-27T19:02:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from . import design_extension_schema, simulation_extension_schema


class AdaDesignAndAnalysisExtension(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    simulation_objects: Optional[List[simulation_extension_schema.SimulationDataExtensionMetadata]] = Field(
        [], description="Array containing Simulation Data objects"
    )
    design_objects: Optional[List[design_extension_schema.DesignDataExtension]] = Field(
        [], description="Array containing Design Data objects"
    )
    version: Optional[str] = Field("1.0.0", description="Version of the ADA GLTF extension schema")
