# generated by datamodel-codegen:
#   filename:  simulation_extension.schema.json
#   timestamp: 2026-05-29T17:55:39+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, confloat, conint


class ElementCounts(BaseModel):
    beam: Optional[conint(ge=0)] = Field(None, description='Line / beam elements.')
    shell: Optional[conint(ge=0)] = Field(None, description='Shell elements.')
    solid: Optional[conint(ge=0)] = Field(None, description='Solid elements.')


class COG(BaseModel):
    x: float
    y: float
    z: float
    total_mass: Optional[confloat(ge=0.0)] = Field(None, description='Sum of contributing masses.')
    total_volume: Optional[confloat(ge=0.0)] = Field(None, description='Sum of contributing volumes.')


class AnalysisType(Enum):
    eigenvalue = 'eigenvalue'
    implicit_static = 'implicit static'
    implicit_dynamic = 'implicit dynamic'
    explicit = 'explicit'


class DataReference(BaseModel):
    bufferView: conint(ge=0) = Field(..., description='Index of the glTF bufferView containing the binary data.')
    byteOffset: Optional[conint(ge=0)] = Field(0, description='Offset into the bufferView in bytes.')


class SimNodeReference(BaseModel):
    points: Optional[str] = Field(None, description='node reference of Point mesh')
    edges: Optional[str] = Field(None, description='node reference of Edges mesh')
    faces: Optional[str] = Field(None, description='node reference of Faces mesh')
    solid_beams: Optional[str] = Field(None, description='node reference of Solid Beams mesh')


class FeObjectType(Enum):
    node = 'node'
    element = 'element'


class SimGroup(BaseModel):
    name: Optional[str] = Field(None, description='Name of group')
    members: Optional[List[str]] = Field(
        None,
        description='Inline list of element/node names. Used for small groups (default threshold <256); large groups switch to members_buffer_view to keep the JSON chunk size bounded.',
    )
    members_buffer_view: Optional[conint(ge=0)] = Field(
        None,
        description="Index of a glTF bufferView holding the packed uint32 member IDs. Mutually exclusive with `members`. Used for large element groups so the JSON chunk doesn't balloon. The IDs are reconstructed into names by prepending `members_prefix`.",
    )
    members_prefix: Optional[str] = Field(
        None,
        description='String prepended to each uint32 ID in members_buffer_view to reconstruct the element/node name (e.g. "EL", "Li", "P"). Required when members_buffer_view is set.',
    )
    description: Optional[str] = Field(None, description='Description of Group')
    parent_name: Optional[str] = Field(None, description='Name of the parent simulation object')
    parent_object_guid: Optional[str] = Field(
        None,
        description='adapy guid of the CAD-side Beam/Plate this SimGroup was meshed from. Lets the viewer link FEA elements back to their CAD parent without name matching. Populated from FemSection.refs[0].guid.',
    )
    fe_object_type: Optional[FeObjectType] = Field(
        None, description='Type of finite element model objects in this group (nodes or elements)'
    )


class SimStats(BaseModel):
    cog: Optional[COG] = Field(
        None,
        description='Mass-weighted centre of gravity. total_mass and total_volume are zero when elements have no material assigned.',
    )
    element_counts: Optional[ElementCounts] = Field(None, description='Number of finite elements per category.')


class FieldObject(BaseModel):
    name: str = Field(..., description='Name of the result field, e.g., displacement, stress.')
    type: str = Field(..., description="Type of the field data, e.g., 'vector', 'scalar'.")
    data: DataReference


class StepObject(BaseModel):
    analysis_type: AnalysisType = Field(..., description='Type of analysis for this step.')
    fields: List[FieldObject] = Field(..., description='List of field data objects for this step.')


class SimulationDataExtensionMetadata(BaseModel):
    name: str = Field(..., description='Name of the simulation.')
    date: datetime = Field(..., description='Date and time of the simulation.')
    fea_software: str = Field(..., description='Name of the FEA software used.')
    fea_software_version: str = Field(..., description='Version of the FEA software.')
    steps: List[StepObject] = Field(..., description='List of analysis steps.')
    node_references: Optional[SimNodeReference] = Field(None, description='References to GLTF node names')
    groups: Optional[List[SimGroup]] = Field(None, description='Named groups and their member objects')
    stats: Optional[SimStats] = Field(
        None,
        description='Aggregate metrics for this simulation model (centre of gravity, element counts). Computed at bake time so the viewer can show per-model info without reloading source.',
    )
