// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ProceduralModelLoad implements flatbuffers.IUnpackableObject<ProceduralModelLoadT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProceduralModelLoad {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProceduralModelLoad(bb:flatbuffers.ByteBuffer, obj?:ProceduralModelLoad):ProceduralModelLoad {
  return (obj || new ProceduralModelLoad()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProceduralModelLoad(bb:flatbuffers.ByteBuffer, obj?:ProceduralModelLoad):ProceduralModelLoad {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProceduralModelLoad()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

modelId():string|null
modelId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
modelId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startProceduralModelLoad(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addModelId(builder:flatbuffers.Builder, modelIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, modelIdOffset, 0);
}

static endProceduralModelLoad(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProceduralModelLoad(builder:flatbuffers.Builder, modelIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  ProceduralModelLoad.startProceduralModelLoad(builder);
  ProceduralModelLoad.addModelId(builder, modelIdOffset);
  return ProceduralModelLoad.endProceduralModelLoad(builder);
}

unpack(): ProceduralModelLoadT {
  return new ProceduralModelLoadT(
    this.modelId()
  );
}


unpackTo(_o: ProceduralModelLoadT): void {
  _o.modelId = this.modelId();
}
}

export class ProceduralModelLoadT implements flatbuffers.IGeneratedObject {
constructor(
  public modelId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const modelId = (this.modelId !== null ? builder.createString(this.modelId!) : 0);

  return ProceduralModelLoad.createProceduralModelLoad(builder,
    modelId
  );
}
}
