// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ProceduralModelLoadReply implements flatbuffers.IUnpackableObject<ProceduralModelLoadReplyT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProceduralModelLoadReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProceduralModelLoadReply(bb:flatbuffers.ByteBuffer, obj?:ProceduralModelLoadReply):ProceduralModelLoadReply {
  return (obj || new ProceduralModelLoadReply()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProceduralModelLoadReply(bb:flatbuffers.ByteBuffer, obj?:ProceduralModelLoadReply):ProceduralModelLoadReply {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProceduralModelLoadReply()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

modelId():string|null
modelId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
modelId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

docJson():string|null
docJson(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
docJson(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

contentHash():string|null
contentHash(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contentHash(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startProceduralModelLoadReply(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addModelId(builder:flatbuffers.Builder, modelIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, modelIdOffset, 0);
}

static addDocJson(builder:flatbuffers.Builder, docJsonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, docJsonOffset, 0);
}

static addContentHash(builder:flatbuffers.Builder, contentHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, contentHashOffset, 0);
}

static endProceduralModelLoadReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProceduralModelLoadReply(builder:flatbuffers.Builder, modelIdOffset:flatbuffers.Offset, docJsonOffset:flatbuffers.Offset, contentHashOffset:flatbuffers.Offset):flatbuffers.Offset {
  ProceduralModelLoadReply.startProceduralModelLoadReply(builder);
  ProceduralModelLoadReply.addModelId(builder, modelIdOffset);
  ProceduralModelLoadReply.addDocJson(builder, docJsonOffset);
  ProceduralModelLoadReply.addContentHash(builder, contentHashOffset);
  return ProceduralModelLoadReply.endProceduralModelLoadReply(builder);
}

unpack(): ProceduralModelLoadReplyT {
  return new ProceduralModelLoadReplyT(
    this.modelId(),
    this.docJson(),
    this.contentHash()
  );
}


unpackTo(_o: ProceduralModelLoadReplyT): void {
  _o.modelId = this.modelId();
  _o.docJson = this.docJson();
  _o.contentHash = this.contentHash();
}
}

export class ProceduralModelLoadReplyT implements flatbuffers.IGeneratedObject {
constructor(
  public modelId: string|Uint8Array|null = null,
  public docJson: string|Uint8Array|null = null,
  public contentHash: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const modelId = (this.modelId !== null ? builder.createString(this.modelId!) : 0);
  const docJson = (this.docJson !== null ? builder.createString(this.docJson!) : 0);
  const contentHash = (this.contentHash !== null ? builder.createString(this.contentHash!) : 0);

  return ProceduralModelLoadReply.createProceduralModelLoadReply(builder,
    modelId,
    docJson,
    contentHash
  );
}
}
