// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ProceduralModelListEntry implements flatbuffers.IUnpackableObject<ProceduralModelListEntryT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProceduralModelListEntry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProceduralModelListEntry(bb:flatbuffers.ByteBuffer, obj?:ProceduralModelListEntry):ProceduralModelListEntry {
  return (obj || new ProceduralModelListEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProceduralModelListEntry(bb:flatbuffers.ByteBuffer, obj?:ProceduralModelListEntry):ProceduralModelListEntry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProceduralModelListEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

modelId():string|null
modelId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
modelId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

contentHash():string|null
contentHash(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contentHash(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

modifiedAt():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

sizeBytes():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startProceduralModelListEntry(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addModelId(builder:flatbuffers.Builder, modelIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, modelIdOffset, 0);
}

static addContentHash(builder:flatbuffers.Builder, contentHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contentHashOffset, 0);
}

static addModifiedAt(builder:flatbuffers.Builder, modifiedAt:bigint) {
  builder.addFieldInt64(2, modifiedAt, BigInt('0'));
}

static addSizeBytes(builder:flatbuffers.Builder, sizeBytes:bigint) {
  builder.addFieldInt64(3, sizeBytes, BigInt('0'));
}

static endProceduralModelListEntry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProceduralModelListEntry(builder:flatbuffers.Builder, modelIdOffset:flatbuffers.Offset, contentHashOffset:flatbuffers.Offset, modifiedAt:bigint, sizeBytes:bigint):flatbuffers.Offset {
  ProceduralModelListEntry.startProceduralModelListEntry(builder);
  ProceduralModelListEntry.addModelId(builder, modelIdOffset);
  ProceduralModelListEntry.addContentHash(builder, contentHashOffset);
  ProceduralModelListEntry.addModifiedAt(builder, modifiedAt);
  ProceduralModelListEntry.addSizeBytes(builder, sizeBytes);
  return ProceduralModelListEntry.endProceduralModelListEntry(builder);
}

unpack(): ProceduralModelListEntryT {
  return new ProceduralModelListEntryT(
    this.modelId(),
    this.contentHash(),
    this.modifiedAt(),
    this.sizeBytes()
  );
}


unpackTo(_o: ProceduralModelListEntryT): void {
  _o.modelId = this.modelId();
  _o.contentHash = this.contentHash();
  _o.modifiedAt = this.modifiedAt();
  _o.sizeBytes = this.sizeBytes();
}
}

export class ProceduralModelListEntryT implements flatbuffers.IGeneratedObject {
constructor(
  public modelId: string|Uint8Array|null = null,
  public contentHash: string|Uint8Array|null = null,
  public modifiedAt: bigint = BigInt('0'),
  public sizeBytes: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const modelId = (this.modelId !== null ? builder.createString(this.modelId!) : 0);
  const contentHash = (this.contentHash !== null ? builder.createString(this.contentHash!) : 0);

  return ProceduralModelListEntry.createProceduralModelListEntry(builder,
    modelId,
    contentHash,
    this.modifiedAt,
    this.sizeBytes
  );
}
}
