// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ProceduralModelSaveReply implements flatbuffers.IUnpackableObject<ProceduralModelSaveReplyT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProceduralModelSaveReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProceduralModelSaveReply(bb:flatbuffers.ByteBuffer, obj?:ProceduralModelSaveReply):ProceduralModelSaveReply {
  return (obj || new ProceduralModelSaveReply()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProceduralModelSaveReply(bb:flatbuffers.ByteBuffer, obj?:ProceduralModelSaveReply):ProceduralModelSaveReply {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProceduralModelSaveReply()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

modelId():string|null
modelId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
modelId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

contentHash():string|null
contentHash(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contentHash(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startProceduralModelSaveReply(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addModelId(builder:flatbuffers.Builder, modelIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, modelIdOffset, 0);
}

static addContentHash(builder:flatbuffers.Builder, contentHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contentHashOffset, 0);
}

static endProceduralModelSaveReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProceduralModelSaveReply(builder:flatbuffers.Builder, modelIdOffset:flatbuffers.Offset, contentHashOffset:flatbuffers.Offset):flatbuffers.Offset {
  ProceduralModelSaveReply.startProceduralModelSaveReply(builder);
  ProceduralModelSaveReply.addModelId(builder, modelIdOffset);
  ProceduralModelSaveReply.addContentHash(builder, contentHashOffset);
  return ProceduralModelSaveReply.endProceduralModelSaveReply(builder);
}

unpack(): ProceduralModelSaveReplyT {
  return new ProceduralModelSaveReplyT(
    this.modelId(),
    this.contentHash()
  );
}


unpackTo(_o: ProceduralModelSaveReplyT): void {
  _o.modelId = this.modelId();
  _o.contentHash = this.contentHash();
}
}

export class ProceduralModelSaveReplyT implements flatbuffers.IGeneratedObject {
constructor(
  public modelId: string|Uint8Array|null = null,
  public contentHash: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const modelId = (this.modelId !== null ? builder.createString(this.modelId!) : 0);
  const contentHash = (this.contentHash !== null ? builder.createString(this.contentHash!) : 0);

  return ProceduralModelSaveReply.createProceduralModelSaveReply(builder,
    modelId,
    contentHash
  );
}
}
