// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ServerProcessInfo implements flatbuffers.IUnpackableObject<ServerProcessInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ServerProcessInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsServerProcessInfo(bb:flatbuffers.ByteBuffer, obj?:ServerProcessInfo):ServerProcessInfo {
  return (obj || new ServerProcessInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsServerProcessInfo(bb:flatbuffers.ByteBuffer, obj?:ServerProcessInfo):ServerProcessInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ServerProcessInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

pid():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

threadId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

logFilePath():string|null
logFilePath(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
logFilePath(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startServerProcessInfo(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPid(builder:flatbuffers.Builder, pid:number) {
  builder.addFieldInt32(0, pid, 0);
}

static addThreadId(builder:flatbuffers.Builder, threadId:number) {
  builder.addFieldInt32(1, threadId, 0);
}

static addLogFilePath(builder:flatbuffers.Builder, logFilePathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, logFilePathOffset, 0);
}

static endServerProcessInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createServerProcessInfo(builder:flatbuffers.Builder, pid:number, threadId:number, logFilePathOffset:flatbuffers.Offset):flatbuffers.Offset {
  ServerProcessInfo.startServerProcessInfo(builder);
  ServerProcessInfo.addPid(builder, pid);
  ServerProcessInfo.addThreadId(builder, threadId);
  ServerProcessInfo.addLogFilePath(builder, logFilePathOffset);
  return ServerProcessInfo.endServerProcessInfo(builder);
}

unpack(): ServerProcessInfoT {
  return new ServerProcessInfoT(
    this.pid(),
    this.threadId(),
    this.logFilePath()
  );
}


unpackTo(_o: ServerProcessInfoT): void {
  _o.pid = this.pid();
  _o.threadId = this.threadId();
  _o.logFilePath = this.logFilePath();
}
}

export class ServerProcessInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public pid: number = 0,
  public threadId: number = 0,
  public logFilePath: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const logFilePath = (this.logFilePath !== null ? builder.createString(this.logFilePath!) : 0);

  return ServerProcessInfo.createServerProcessInfo(builder,
    this.pid,
    this.threadId,
    logFilePath
  );
}
}
