"""Generate the frontend's AFBS fixture from the Python reference expander.

The compact beam-solids artefact is expanded twice — once in
``ada.fem.results.artefacts.beam_compact`` for the parity test and any
server-side consumer, once in TypeScript for the viewer — and the two have to
agree bit for bit or a beam's vertices land in a different place depending on
who drew them. A shared fixture is how that is kept honest: this script writes
a tiny AFBS file plus the exact arrays the Python expander produces from it,
and the frontend test asserts its own expander reproduces them.

Two beams on two sections, chosen to exercise what actually differs between
implementations rather than to look like a model:

* a 4-point rectangular outline and a 3-point triangular one, so the section
  table has more than one entry and the section index is load-bearing;
* the second beam's endpoints are NOT the ends of its extrusion (it carries
  unequal eccentricities), so its frame axis tilts away from the element axis
  and ``t`` varies around a ring — the case that rules out shipping ``t`` per
  section and the one an implementation is most likely to get wrong;
* a main point buffer whose coordinates are exactly representable in float32,
  so "the same number" means the same number on both sides.

Run it from the repo root; ``tests/core/fem/results/test_beam_compact.py``
re-runs it and fails if the committed bytes have gone stale.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

import numpy as np

# Relative to the repo root.
FIXTURE_DIR = pathlib.Path("src/frontend/src/__tests__/fixtures/beam_solids_compact")
BIN_NAME = "two_beams.bin"
JSON_NAME = "two_beams.expected.json"


def build_instances():
    """The two beams, as ``(instances, main_points)``."""

    from ada import Beam, Section
    from ada.api.curves import CurvePoly2d
    from ada.fem.results.artefacts.beam_compact import collect_beam_solid_instances

    # Rectangle and triangle, both as explicit polygons so the outline
    # sampler returns exactly 4 and 3 points and the fixture stays readable.
    rect = Section(
        "FixtureRect",
        "poly",
        outer_poly=CurvePoly2d(
            [(-0.25, -0.125), (0.25, -0.125), (0.25, 0.125), (-0.25, 0.125)],
            (0, 0, 0),
            (0, 0, 1),
            (1, 0, 0),
        ),
    )
    tri = Section(
        "FixtureTri",
        "poly",
        outer_poly=CurvePoly2d(
            [(-0.2, -0.1), (0.2, -0.1), (0.0, 0.2)],
            (0, 0, 0),
            (0, 0, 1),
            (1, 0, 0),
        ),
    )

    # float32-exact coordinates: every value a dyadic rational, so the number
    # the JSON carries, the number numpy sees and the number JavaScript reads
    # out of a Float32Array are one number.
    points = np.array(
        [
            [0.0, 0.0, 0.0],
            [4.0, 0.0, 0.0],
            [0.0, 2.5, 0.0],
            [3.0, 2.5, 0.5],
        ],
        dtype=np.float64,
    )

    b0 = Beam("fixture0", (0, 0, 0), (4, 0, 0), sec=rect, up=(0, 0, 1))
    # Unequal end offsets: the extrusion axis is no longer the element axis,
    # so t is not constant around a ring.
    b1 = Beam("fixture1", (0, 2.5, 0), (3, 2.5, 0.5), sec=tri, up=(0, 0, 1))
    b1.e1 = np.array([0.0, 0.03125, 0.0])
    b1.e2 = np.array([0.0, -0.03125, 0.0])

    beams = [
        (b0, 101, 0, 1, points[0], points[1]),
        (b1, 202, 2, 3, points[2], points[3]),
    ]
    inst = collect_beam_solid_instances(beams, total_beams=len(beams))
    if inst is None:
        raise SystemExit("fixture beams produced no instances")
    return inst, points


def build_fixture() -> tuple[bytes, dict]:
    """Return the AFBS bytes and the expected-arrays payload."""

    import tempfile

    from ada.fem.results.artefacts.beam_compact import (
        expand_beam_solid_instances,
        read_beam_solids_compact,
        write_beam_solids_compact,
    )

    inst, points = build_instances()

    with tempfile.TemporaryDirectory() as td:
        path = pathlib.Path(td) / BIN_NAME
        write_beam_solids_compact(inst, path)
        blob = path.read_bytes()
        # Expand what the FILE says, not what the collector held: the frontend
        # only ever sees the file, so the expectations must come from it too.
        expanded = expand_beam_solid_instances(read_beam_solids_compact(path), points)

    payload = {
        "comment": (
            "Generated by tools/gen_beam_solids_compact_fixture.py — do not hand-edit. "
            "mainPositions is the main FEA mesh point buffer that node0/node1 index."
        ),
        "mainPositions": [float(v) for v in points.astype(np.float32).ravel()],
        "nVerts": int(expanded.points.shape[0]),
        "positions": [float(v) for v in np.asarray(expanded.points, dtype=np.float32).ravel()],
        "indices": [int(v) for v in np.asarray(expanded.triangles, dtype=np.uint32).ravel()],
        "drawRanges": [
            {"label": int(r.label), "triStart": int(r.tri_start), "triCount": int(r.tri_count)}
            for r in expanded.element_ranges
        ],
        "node0": [int(v) for v in expanded.vertex_node0],
        "node1": [int(v) for v in expanded.vertex_node1],
        "t": [float(v) for v in np.asarray(expanded.vertex_t, dtype=np.float32)],
    }
    return blob, payload


def payload_bytes(payload: dict) -> bytes:
    """JSON as it is committed — stable key order, trailing newline."""

    return (json.dumps(payload, indent=2) + "\n").encode("utf-8")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--root",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parents[1],
        help="repository root (default: the checkout this script lives in)",
    )
    ap.add_argument("--check", action="store_true", help="fail instead of writing when stale")
    args = ap.parse_args(argv)

    out_dir = args.root / FIXTURE_DIR
    blob, payload = build_fixture()
    js = payload_bytes(payload)

    if args.check:
        stale = []
        for name, want in ((BIN_NAME, blob), (JSON_NAME, js)):
            path = out_dir / name
            if not path.exists() or path.read_bytes() != want:
                stale.append(str(path))
        if stale:
            print("stale fixture(s):\n  " + "\n  ".join(stale), file=sys.stderr)
            return 1
        print("fixtures are current")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / BIN_NAME).write_bytes(blob)
    (out_dir / JSON_NAME).write_bytes(js)
    print(f"wrote {out_dir / BIN_NAME} ({len(blob)} bytes) and {out_dir / JSON_NAME}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
