name: adadocs
channels:
  - krande/label/dev
  - conda-forge
dependencies:
  - python==3.9
  - ada-py
  - ipywidgets
  - sphinx
  - nbsphinx
  - scipy
  - pip
  - pip:
      - sphinx-rtd-theme
      - furo
