name: ci-profiling

# Bump 3
on:
  workflow_dispatch:

jobs:
  test-profile:
    name: Profile ada-py-full
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          cache-env: true
          environment-name: ada
          channels: conda-forge
          channel-priority: strict
          environment-file: conda/environment.core.yml
          create-args: >-
            python=3.11
            jupyterlab
            pyparsing
            pytest
            scalene

      - name: pip install
        run: |
          pip install -e .

      - name: Profile using scalene
        run: scalene --json -m pytest ./tests --ignore=./tests/docker/ --outfile=profile.json

      - name: Profile using cProfile
        run: python -m cProfile -o profile -m pytest tests --ignore=./tests/docker

      - name: Create Release Package
        uses: softprops/action-gh-release@v2
        with:
          files: |
            profile.json
            profile
          tag_name: "Ada-py profile $(date +'%Y-%m-%d %H:%M')"
          body: "Profile produced on commit ${{ github.sha }}"