name: ci-profiling

# Bump 3
on:
  workflow_dispatch:

jobs:
  test-profile:
    name: Profile ada-py-full
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.9.2 # https://github.com/prefix-dev/setup-pixi
        with:
          pixi-version: v0.55.0
          environments: profile
          cache: true

      - name: Run Scalene Profiling
        run: pixi run scalene

      - name: Run cprofilev Profiling
        run: pixi run cprofile

      - name: Create Release Package
        uses: softprops/action-gh-release@v2
        with:
          files: |
            profile.json
            profile
          tag_name: "Ada-py profile $(date +'%Y-%m-%d %H:%M')"
          body: "Profile produced on commit ${{ github.sha }}"