name: ci-release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  pypi:
    if: ${{ github.event.pull_request.merged }}
    name: Publish to PYPI
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Build and upload package for pypi
        shell: bash -l {0}
        run: |
          pip install build
          python -m build
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  conda:
    if: ${{ github.event.pull_request.merged }}
    name: Publish to CONDA
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        build: [ { name: 'core' },{ name: 'full' } ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main # https://github.com/mamba-org/provision-with-micromamba
        with:
          cache-env: true
          channels: conda-forge
          channel-priority: strict
          environment-file: conda/environment.build.yml

      - name: Build & Upload to CONDA Main
        run: |
          conda build -c conda-forge -c krande . --variants "{'variant': '${{matrix.build.name}}'}" --user krande --token=${{ secrets.ANACONDA_TOKEN }} --no-copy-test-source-files --no-test --no-build-id
        working-directory: conda