name: Create Tag on PR Merge

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: release-${{ github.sha }}
  cancel-in-progress: true

jobs:
  release_if_ok:
    if: github.event.pull_request.merged == true
    uses: AibelDevs/action-toolbox/.github/workflows/tool-generate-semantic-version.yaml@main
    secrets:
      SOURCE_KEY: ${{ secrets.SOURCE_KEY }}
